@HOST = https://localhost:6060


GET {{HOST}}/products

###


GET {{HOST}}/products/01911d91-2aa3-40a5-9c32-51c20d1f5e83

###


GET {{HOST}}/products/category/Smart%20Phone

###

POST {{HOST}}/products
Content-Type : application/json

{
  "categories": ["Food", "Fruit"],
  "description": "Delicious Red Apples",
  "price": 9.95,
  "imageFile": "red-apples.jpg"
}

###

PUT {{HOST}}/products
Content-Type : application/json

{
  "id": "019118c9-85ff-4ed9-8c00-e81876f6d79b",
  "name": "Apples",
  "categories": ["Food", "Fruit"],
  "description": "Delicious Red Apples",
  "price": 10.95,
  "imageFile": "red-apples.jpg"
}

###

DELETE {{HOST}}/products/01911d90-3d43-4be0-8757-7e0de0d4afa8

### 

GET {{HOST}}/health

