@HOST = https://localhost:5051
@USERNAME = swn

### 
GET {{HOST}}/baskets/{{USERNAME}}

###
POST {{HOST}}/baskets/{{USERNAME}}
Content-Type : application/json
{
	"cart": 
    {
      "userName": "swn",
      "items": [
        {
          "quantity": 2,
          "color": "Red",
          "price": 500,
          "productId": "5334c996-8457-4cf0-815c-ed2b77c4ff61",
          "productName": "IPhone X"
        },
        {
          "quantity": 1,
          "color": "Blue",
          "price": 500,
          "productId": "c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914",
          "productName": "Samsung 10"
        }
      ]  
    }
}

###
DELETE {{HOST}}/baskets/{{USERNAME}}