version: '3.4'

services:
  catalogdb:
    image: postgres:latest

  basketdb:
    image: postgres:latest

  distributedcache:
    image: redis:latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  baskets.api:
    image: ${DOCKER_REGISTRY-}basketsapi
    build:
      context: .
      dockerfile: Services/Baskets/Baskets.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


